### ISSUE TITLE
64位libffmpeg.so

### ISSUE THREAD

**Issue by WarmPure** [tangyxgit/FFmpegVideo#13]
应用商店需要更新64位so库，可以更新64位libffmpeg.so版本吗？

**Comment by tangyxgit** [comment]
https://www.jianshu.com/p/dfe9404e001a 需要根据这篇文章自己也可以生成哟。项目的确很久没更新了。
________________________________
发件人: 蜗牛君子 ***@***.***>
发送时间: 2023年10月18日 14:48
收件人: tangyxgit/FFmpegVideo ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [tangyxgit/FFmpegVideo] 64位libffmpeg.so (Issue #13)


Closed #13<https://github.com/tangyxgit/FFmpegVideo/issues/13> as completed.

―
